const SUPABASE_URL=window.SUPABASE_CONFIG?.url||'';
const SUPABASE_KEY=window.SUPABASE_CONFIG?.key||'';
const DEPARTMENT_SLUG=window.SUPABASE_CONFIG?.departmentSlug||'';
const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const table='attendance_groups';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let editingId=null,departmentId=null;
async function loadUser(){const {data,error}=await client.auth.getUser();if(error||!data.user){$('#loginView').hidden=false;$('#appView').hidden=true;return;}try{const {data:profile,error:pErr}=await client.from('admin_profiles').select('user_id,department_id,departments!inner(id,name,slug)').eq('user_id',data.user.id).single();if(pErr)throw pErr;if(!profile||profile.departments.slug!==DEPARTMENT_SLUG){await client.auth.signOut();$('#loginView').hidden=false;$('#appView').hidden=true;$('#loginError').textContent='This account is not authorised for this department.';return;}departmentId=profile.department_id;$('#loginView').hidden=true;$('#appView').hidden=false;$('#adminEmail').textContent=data.user.email;loadGroups();}catch(e){console.error(e);await client.auth.signOut();$('#loginView').hidden=false;$('#appView').hidden=true;$('#loginError').textContent='Administrator profile not configured for this department.';}}
async function loadGroups(){const {data,error}=await client.from(table).select('*').eq('department_id',departmentId).order('group_name');if(error){$('#adminStatus').textContent=error.message;return;}$('#rows').innerHTML=(data||[]).map(g=>`<tr><td>${esc(g.group_name)}</td><td>${Number(g.attendance).toFixed(1)}%</td><td>${Number(g.punctuality).toFixed(1)}%</td><td><button class="edit" data-id="${g.id}">Edit</button> <button class="delete" data-id="${g.id}">Delete</button></td></tr>`).join('');document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>editGroup(b.dataset.id,data));document.querySelectorAll('.delete').forEach(b=>b.onclick=()=>deleteGroup(b.dataset.id));}
function editGroup(id,data){const g=data.find(x=>x.id===id);if(!g)return;editingId=id;$('#groupName').value=g.group_name;$('#attendance').value=g.attendance;$('#punctuality').value=g.punctuality;$('#saveBtn').textContent='Update group';window.scrollTo({top:0,behavior:'smooth'});}
async function deleteGroup(id){if(!confirm('Delete this group?'))return;const {error}=await client.from(table).delete().eq('id',id).eq('department_id',departmentId);if(error)alert(error.message);else loadGroups();}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';const {error}=await client.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)$('#loginError').textContent=error.message;else loadUser();});
$('#logout').onclick=async()=>{await client.auth.signOut();loadUser();};
$('#groupForm').addEventListener('submit',async e=>{e.preventDefault();const payload={department_id:departmentId,group_name:$('#groupName').value.trim(),attendance:Number($('#attendance').value),punctuality:Number($('#punctuality').value)};if(!payload.group_name)return;let res=editingId?await client.from(table).update({group_name:payload.group_name,attendance:payload.attendance,punctuality:payload.punctuality}).eq('id',editingId).eq('department_id',departmentId):await client.from(table).insert(payload);if(res.error)$('#adminStatus').textContent=res.error.message;else{$('#adminStatus').textContent='Saved successfully';$('#groupForm').reset();editingId=null;$('#saveBtn').textContent='Add group';loadGroups();}});
loadUser();
